"""added dungeon PK

Revision ID: 04aba775efb5
Revises: d6f82fa53dd0
Create Date: 2020-12-14 18:59:49.125739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04aba775efb5'
down_revision = 'd6f82fa53dd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character_dungeon', sa.Column('completed_at', sa.String(length=128), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('character_dungeon', 'completed_at')
    # ### end Alembic commands ###
