"""added pvp

Revision ID: 12ebd5d51e6d
Revises: 04aba775efb5
Create Date: 2020-12-16 19:39:13.455535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12ebd5d51e6d'
down_revision = '04aba775efb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character_pvp',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('pvp_type', sa.String(length=64), nullable=False),
    sa.Column('season', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('season_won', sa.Integer(), nullable=True),
    sa.Column('season_lost', sa.Integer(), nullable=True),
    sa.Column('weekly_won', sa.Integer(), nullable=True),
    sa.Column('weekly_lost', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['guild_player.player_id'], ),
    sa.PrimaryKeyConstraint('player_id', 'pvp_type')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('character_pvp')
    # ### end Alembic commands ###
