"""last_modified

Revision ID: 18b16a67f0d6
Revises: 061158b34d68
Create Date: 2020-12-10 21:39:48.487824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18b16a67f0d6'
down_revision = '061158b34d68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guild', sa.Column('last_modified', sa.DateTime(), nullable=True))
    op.add_column('guild_player', sa.Column('last_modified', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guild_player', 'last_modified')
    op.drop_column('guild', 'last_modified')
    # ### end Alembic commands ###
