"""hotfix2

Revision ID: 54c228e72d50
Revises: 42c81c412525
Create Date: 2020-12-12 08:36:41.451754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54c228e72d50'
down_revision = '42c81c412525'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'character_equipment', ['item_id', 'slot', 'player_id'])
    op.create_unique_constraint(None, 'guild', ['guild_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'guild', type_='unique')
    op.drop_constraint(None, 'character_equipment', type_='unique')
    # ### end Alembic commands ###
