"""raid progress

Revision ID: 603649d41fbd
Revises: 12ebd5d51e6d
Create Date: 2020-12-16 20:23:10.820943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '603649d41fbd'
down_revision = '12ebd5d51e6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guild_player', sa.Column('heroic_bosses', sa.Integer(), nullable=True))
    op.add_column('guild_player', sa.Column('mythic_bosses', sa.Integer(), nullable=True))
    op.add_column('guild_player', sa.Column('normal_bosses', sa.Integer(), nullable=True))
    op.add_column('guild_player', sa.Column('raid_summary', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guild_player', 'raid_summary')
    op.drop_column('guild_player', 'normal_bosses')
    op.drop_column('guild_player', 'mythic_bosses')
    op.drop_column('guild_player', 'heroic_bosses')
    # ### end Alembic commands ###
