"""added mounts

Revision ID: 61cf9c5d7755
Revises: f19eed045826
Create Date: 2020-12-14 06:38:23.298396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61cf9c5d7755'
down_revision = 'f19eed045826'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character_mount',
    sa.Column('mount_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('useable', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['guild_player.player_id'], ),
    sa.PrimaryKeyConstraint('mount_id', 'player_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('character_mount')
    # ### end Alembic commands ###
