"""legy spell

Revision ID: b29f3f891ee1
Revises: 7fb4426605a8
Create Date: 2020-12-12 22:16:54.162966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b29f3f891ee1'
down_revision = '7fb4426605a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character_equipment', sa.Column('legy_spell', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('character_equipment', 'legy_spell')
    # ### end Alembic commands ###
