"""lm_changes

Revision ID: d3afce3ef9ef
Revises: 18b16a67f0d6
Create Date: 2020-12-11 12:37:50.314857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3afce3ef9ef'
down_revision = '18b16a67f0d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guild_player', 'character_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guild_player', sa.Column('character_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
