"""updated dungeons

Revision ID: d6f82fa53dd0
Revises: 61cf9c5d7755
Create Date: 2020-12-14 18:46:34.580121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6f82fa53dd0'
down_revision = '61cf9c5d7755'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character_dungeon', sa.Column('dungeon_short', sa.String(length=16), nullable=True))
    op.add_column('character_dungeon', sa.Column('dungeon_type', sa.String(length=128), nullable=False))
    op.add_column('character_dungeon', sa.Column('keystone_upgrades', sa.Integer(), nullable=True))
    op.add_column('character_dungeon', sa.Column('score', sa.Float(), nullable=True))
    op.drop_column('character_dungeon', 'dungeon_period')
    op.drop_column('character_dungeon', 'intime')
    op.add_column('guild_player', sa.Column('achievement_points', sa.Integer(), nullable=True))
    op.add_column('guild_player', sa.Column('active_spec_name', sa.String(length=32), nullable=True))
    op.add_column('guild_player', sa.Column('active_spec_role', sa.String(length=32), nullable=True))
    op.add_column('guild_player', sa.Column('covenant', sa.String(length=32), nullable=True))
    op.add_column('guild_player', sa.Column('mythic_rio', sa.Float(), nullable=True))
    op.add_column('guild_player', sa.Column('renown_level', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guild_player', 'renown_level')
    op.drop_column('guild_player', 'mythic_rio')
    op.drop_column('guild_player', 'covenant')
    op.drop_column('guild_player', 'active_spec_role')
    op.drop_column('guild_player', 'active_spec_name')
    op.drop_column('guild_player', 'achievement_points')
    op.add_column('character_dungeon', sa.Column('intime', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('character_dungeon', sa.Column('dungeon_period', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('character_dungeon', 'score')
    op.drop_column('character_dungeon', 'keystone_upgrades')
    op.drop_column('character_dungeon', 'dungeon_type')
    op.drop_column('character_dungeon', 'dungeon_short')
    # ### end Alembic commands ###
